### ISSUE TITLE
Create Bank with any charecters 4 charecters of alredy existed bankname and concat with other charecter. (TC_bankapp_API_BC_017)

### ISSUE THREAD

**Issue by AbhijithTyss** [AbhijithTyss/DemoBankApp_repo#2]
Try to create bank with 5 characters. Use 4 characters of already existed bank name and add one more character to that.
![bug-2](https://github.com/AbhijithTyss/DemoBankApp_repo/assets/145775712/ed8c2eab-e939-4f49-83d4-7aeff08d4e67)

**Comment by manoj-65** [comment]
it's fixed.. you can check.
