### ISSUE TITLE
"Verify the admin is able to create bank with lessthan 4 charecters of bank name"( TC_bankapp_API_BC_004 )

### ISSUE THREAD

**Issue by AbhijithTyss** [AbhijithTyss/DemoBankApp_repo#3]
Try to create bank with less than 4 characters
expected : bank should be created
actual: unauthorized error message is displaying
![bug-3](https://github.com/AbhijithTyss/DemoBankApp_repo/assets/145775712/a75dfdb3-1147-4191-be05-e89c1bd32f23)

**Comment by manoj-65** [comment]
Issues Fixed.
![TC_bankapp_API_BC_004](https://github.com/AbhijithTyss/DemoBankApp_repo/assets/132426541/f0bec839-5221-42c2-9f0f-afcc48a2e5bb)
