### ISSUE TITLE
Verify the admin is able to create Managing Director(TC_bankapp_API_MD_001)

### ISSUE THREAD

**Issue by AbhijithTyss** [AbhijithTyss/DemoBankApp_repo#4]
After creating managing director managingDirectorId should be displayed, employeeId is displaying
![bug-4](https://github.com/AbhijithTyss/DemoBankApp_repo/assets/145775712/295b0acf-b7fb-4e2b-8e98-b4a1c4cca686)

**Comment by manoj-65** [comment]
Field name modified and in the next build changes will be reflected.
