### ISSUE TITLE
Verify admin is able to create bank with same name which is already existed(TC_bankapp_API_BC_018)

### ISSUE THREAD

**Issue by AbhijithTyss** [AbhijithTyss/DemoBankApp_repo#7]
When admin tries to create bank with same name which is already existed in database, he should get duplicate entry message.

Expected:
1. Duplicate Entry message should be displayed

Actual:
1. Bank is created

**Comment by manoj-65** [comment]
In the initial requirement the name was not unique so it was designed to  accept the duplicate name's and as we are going to generate the bankId based on the first 4 characters of the bank name we will make the bank name unique in the final build
